questions =  [
    {"id": 0, "question": "Landlords do not make any real contribution to our society.", "effects": {"right": -1}},
    {"id": 1, "question": "Billionaires should not exist.", "effects": {"right": -2}},
    {"id": 2, "question": "Money would not exist in an ideal society.", "effects": {"right": -1}},
    {"id": 3, "question": "Humans have no fixed nature.", "effects": {"right": -1}},
    {"id": 4, "question": "Accumulation of wealth leads to the creation of an opressive class system", "effects": {"right": -2}},
    {"id": 5, "question": "The value of something comes from the work that goes into creating it.", "effects": {"right": -1}},
    {"id": 6, "question": "Most rich people make their fortunes dishonestly", "effects": {"right": -1}},
    {"id": 7, "question": "Private property should be abolished.", "effects": {"right": -2}},
    {"id": 8, "question": "Goods should be produced to be used, not to make a profit.", "effects": {"right": -1}},
    {"id": 9, "question": "Violent revolution is necessary to make serious change.", "effects": {"right": -1}},
    {"id": 10, "question": "We must completely reorder society to stop global warming.", "effects": {"right": -1}},

    {"id": 11, "question": "Rich people deserve to have access to higher quality healthcare", "effects": {"right": 1}},
    {"id": 12, "question": "Wages are always fair if set by the market.", "effects": {"right": 2}},
    {"id": 13, "question": "Competition is necessary for innovation.", "effects": {"right": 2}},
    {"id": 14, "question": "Investors should be rewarded for their investments.", "effects": {"right": 1}},
    {"id": 15, "question": "Stealing is never morally permissible.", "effects": {"right": 1}},
    {"id": 16, "question": "Inheritance is a legitemate way to aquire wealth.", "effects": {"right": 1}},
    {"id": 17, "question": "The wealth gained from extracting natural resources belongs to the landowner", "effects": {"right": 1}},
    {"id": 18, "question": "Workers could never have the skills necessary to control their workplaces.", "effects": {"right": 1}},
    {"id": 19, "question": "Companies are not oppressive when employees are free to quit.", "effects": {"right": 2}},
    {"id": 20, "question": "Inequality is necessary for prosperity.", "effects": {"right": 1}},
    {"id": 21, "question": "Those who do not work should starve.", "effects": {"right": 1}},

    {"id": 22, "question": "Freedom of speech is vital for a healthy society.", "effects": {"auth": -1}},
    {"id": 23, "question": "The government should be less involved in people’s everyday lives.", "effects": {"auth": -2}},
    {"id": 24, "question": "People should come together to form independent and self governing communities.", "effects": {"auth": -1}},
    {"id": 25, "question": "Nobody should be forced to work if they do not want to.", "effects": {"auth": -2}},
    {"id": 26, "question": "Prostitution should be legal.", "effects": {"auth": -1}},
    {"id": 27, "question": "We must severely reduce our military spending.", "effects": {"auth": -1}},
    {"id": 28, "question": "People should be free to practice any religion as long as they aren’t harming others.", "effects": {"auth": -1}},
    {"id": 29, "question": "Nobody should have access to my information without my consent.", "effects": {"auth": -1}},
    {"id": 30, "question": "Victimless crimes should not be crimes at all.", "effects": {"auth": -2}},
    {"id": 31, "question": "People have the right to fight the police in self defence.", "effects": {"auth": -1}},
    {"id": 32, "question": "Big corporations and governments collude to wipe out small businesses.", "effects": {"auth": -1}},

    {"id": 33, "question": "People generally don’t know what’s best for themselves.", "effects": {"auth": 1}},
    {"id": 34, "question": "Organisations which oppose the government should be forcefully disbanded.", "effects": {"auth": 2}},
    {"id": 35, "question": "Gaining control of the state is the most important step to achieving my goals.", "effects": {"auth": 2}},
    {"id": 36, "question": "Bureaucracy is necessary for society to function.", "effects": {"auth": 1}},
    {"id": 37, "question": "Certain beliefs are too harmful to be allowed to be heard in public.", "effects": {"auth": 1}},
    {"id": 38, "question": "My values should be promoted by force if necessary.", "effects": {"auth": 1}},
    {"id": 39, "question": "Democracy hinders the government’s ability to change society for the better.", "effects": {"auth": 1}},
    {"id": 40, "question": "It is necessary to maintain law and order.", "effects": {"auth": 1}},
    {"id": 41, "question": "A society without a state would quickly collapse.", "effects": {"auth": 2}},
    {"id": 42, "question": "Certain rules and regulations should be consistent throughout a country.", "effects": {"auth": 1}},
    {"id": 43, "question": "A stronger government would be able to fix more of society's problems.", "effects": {"auth": 1}},

    {"id": 44, "question": "Abandoned property should be free to use by any individual.", "effects": {"auth": -1, "right": -1}},
    {"id": 45, "question": "Intellectual property is illegitimate.", "effects": {"auth": -1, "right": -1}},
    {"id": 46, "question": "The workplace should be more democratic.", "effects": {"auth": -1, "right": -1}},
    {"id": 47, "question": "Instead of voting for politicians, people should vote on individual issues.", "effects": {"auth": -1, "right": -1}},
    {"id": 48, "question": "People should be free to roam the landscapes of the world.", "effects": {"auth": -1, "right": -1}},
    {"id": 49, "question": "Trespassing should not be a crime.", "effects": {"auth": -1, "right": -1}},
    {"id": 50, "question": "Rehabilitation, not punishment, should be the focus of criminal justice.", "effects": {"auth": -1, "right": -1}},
    {"id": 51, "question": "Political and economic power should be dispersed amongst the population.", "effects": {"auth": -1, "right": -1}},
    {"id": 52, "question": "Workers should be allowed to quit their job whenever they feel like it", "effects": {"auth": -1, "right": -1}},

    {"id": 53, "question": "Taxation is theft.", "effects": {"auth": -1, "right": 1}},
    {"id": 54, "question": "Income taxes should be reduced if not abolished.", "effects": {"auth": -1, "right": 1}},
    {"id": 55, "question": "The economy works best when government intervention is minimal.", "effects": {"auth": -1, "right": 1}},
    {"id": 56, "question": "Free trade between nations is a good thing.", "effects": {"auth": -1, "right": 1}},
    {"id": 57, "question": "“Society” does not really exist.", "effects": {"auth": -1, "right": 1}},
    {"id": 58, "question": "Selfishness can be a virtue.", "effects": {"auth": -1, "right": 1}},
    {"id": 59, "question": "Regulation can often hurt the people it aims to protect.", "effects": {"auth": -1, "right": 1}},
    {"id": 60, "question": "The trade of human organs should be legal.", "effects": {"auth": -1, "right": 1}},
    {"id": 61, "question": "The minimum wage should be abolished.", "effects": {"auth": -1, "right": 1}},

    {"id": 62, "question": "All major industries should be nationalised.", "effects": {"auth": 1, "right": -1}},
    {"id": 63, "question": "The individual has a duty to sacrifice themselves for the good of society.", "effects": {"auth": 1, "right": -1}},
    {"id": 64, "question": "Only licenced surgions should be allowed to perform surgery", "effects": {"auth": 1, "right": -1}},
    {"id": 65, "question": "The government should tax goods which are harmful to society.", "effects": {"auth": 1, "right": -1}},
    {"id": 66, "question": "The economy should be directed away from producing luxuries.", "effects": {"auth": 1, "right": -1}},
    {"id": 67, "question": "The government should provide housing for all citizens.", "effects": {"auth": 1, "right": -1}},
    {"id": 68, "question": "Every child should recieve an equal education.", "effects": {"auth": 1, "right": -1}},
    {"id": 69, "question": "Nobody can ever truly be separate from society.", "effects": {"auth": 1, "right": -1}},
    {"id": 70, "question": "Consumerism has degraded our society.", "effects": {"auth": 1, "right": -1}},

    {"id": 71, "question": "Laws should be in place to prevent workers from unionising.", "effects": {"auth": 1, "right": 1}},
    {"id": 72, "question": "Absolute autocracy is a desirable system of government.", "effects": {"auth": 1, "right": 1}},
    {"id": 73, "question": "Large organisations need a top down structure to function well.", "effects": {"auth": 1, "right": 1}},
    {"id": 74, "question": "Work makes people stronger.", "effects": {"auth": 1, "right": 1}},
    {"id": 75, "question": "Aristocratic societies were better than democratic ones.", "effects": {"auth": 1, "right": 1}},
    {"id": 76, "question": "A society without strong leaders is destined to fail.", "effects": {"auth": 1, "right": 1}},
    {"id": 77, "question": "Workers in essential parts of the economy should not be allowed to strike.", "effects": {"auth": 1, "right": 1}},
    {"id": 78, "question": "Hierarchy will arise in any society.", "effects": {"auth": 1, "right": 1}},
    {"id": 79, "question": "Some people are simply not worthy of moral consideration.", "effects": {"auth": 1, "right": 1}},
];
